name: athena
description: "Library Digital"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.4
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.4
  image_picker: ^0.8.7+5
  reorderables: ^0.4.4
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.0.1
  google_fonts: ^6.2.1
  get: ^4.6.5
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/home.png
    - assets/images/home1.png
    - assets/images/search.png
    - assets/images/search1.png
    - assets/images/user.png
    - assets/images/user1.png
    - assets/images/add.png
    - assets/images/add1.png
    - assets/images/settings-sliders.png
    - assets/images/onboarding.png
    - assets/images/inbox-full (1).png
    - assets/images/inbox-full.png
    - assets/lottie/splashscreen.json
    - assets/lottie/books.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
